options {
    DEBUG_PARSER = true;
    STATIC = false;
}

PARSER_BEGIN(Example)

package org.example.parser;

/** Simple brace matcher. */
public class Example {
    public Example(){
        super();
    }
}

PARSER_END(Example)

/** Root production. */
void Input() :
{}
{
  MatchedBraces() ("\n"|"\r")* <EOF>
}

/** Brace matching production. */
void MatchedBraces() :
{}
{
  "{" [ MatchedBraces() ] "}"
}
